version: '2'
services:
  dev:
    build:
      context: .
      dockerfile: dev.docker
    container_name: dev
    tty: true
    stdin_open: true
    volumes:
      - ./config/dev/.bashrc:/root/.bashrc
      - ./apps:/root/apps

  web1:
    build:
      context: .
      dockerfile: ruby.docker

  web2:
    build:
      context: .
      dockerfile: ruby.docker

  web:
    image: haproxy:latest
    depends_on:
      - web1
      - web2
    links:
      - web1
      - web2
    command: bash -c "sleep 5 && haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "3000:80"

  utility1:
    build:
      context: .
      dockerfile: java.docker

  logstash:
    image: logstash:latest

  elasticsearch:
    image: elasticsearch:latest
    volumes:
      - ./config/elasticshearch:/usr/share/elasticsearch/config

  kibana:
    image: kibana:latest

  ci:
    image: jenkins:latest

  gitlab:
    image: gitlab/gitlab-ce:latest

