version: '2'
services:
  web-1:
    build:
      context: '.'
      dockerfile: 'Dockerfile-ruby'

  web-2:
    build:
      context: '.'
      dockerfile: 'Dockerfile-ruby'

  data-1:
    build:
      context: '.'
      dockerfile: 'Dockerfile-java'

  ci:
    image: 'jenkins:latest'

  gitlab:
    image: 'gitlab/gitlab-ce:latest'

  logstash:
    image: 'logstash:latest'

  elasticsearch:
    image: 'elasticsearch:latest'
    volumes:
      - ./config/elasticshearch:/usr/share/elasticsearch/config

  kibana:
    image: 'kibana:latest'
